DROP TABLE IF EXISTS fb00_uda03430.rome_fap_pcs_tmp;
CREATE EXTERNAL TABLE IF NOT EXISTS fb00_uda03430.rome_fap_pcs_tmp (
    ROME STRING, FAP STRING, PCS STRING)
ROW FORMAT DELIMITED FIELDS TERMINATED BY '|'
STORED AS TEXTFILE LOCATION 'hdfs://haclushp01/user/fb00_xda034/tmp';

DROP TABLE IF EXISTS fb00_uda03430.rome_fap_pcs;
CREATE TABLE fb00_uda03430.rome_fap_pcs
STORED AS ORC AS SELECT
* 
FROM fb00_uda03430.rome_fap_pcs_tmp;
